# Generated by Django 2.2.6 on 2019-10-11 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email')),
                ('password', models.CharField(max_length=16, verbose_name='Senha')),
                ('nome', models.CharField(max_length=32, verbose_name='Nome')),
                ('data_nascimento', models.DateField()),
                ('cep', models.TextField(max_length=9)),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('NB', 'Não-Binário')], max_length=13, verbose_name='gender')),
            ],
        ),
    ]
