# Generated by Django 2.2.6 on 2019-10-14 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20191011_1913'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item_achado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('local', models.TextField()),
                ('data', models.DateField(null=True)),
                ('tags', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Item_perdido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('local', models.TextField()),
                ('data', models.DateField(null=True)),
                ('tags', models.TextField()),
            ],
        ),
    ]
