# Generated by Django 2.2.6 on 2019-10-16 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_item_achado_item_perdido'),
    ]

    operations = [
        migrations.AddField(
            model_name='item_achado',
            name='pessoa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='website.Pessoa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item_perdido',
            name='pessoa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='website.Pessoa'),
            preserve_default=False,
        ),
    ]
