# Generated by Django 2.2.6 on 2019-10-23 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20191016_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='item_achado',
            name='imagem',
            field=models.ImageField(default=1, upload_to='static/images'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item_perdido',
            name='imagem',
            field=models.ImageField(default=2, upload_to='static/images'),
            preserve_default=False,
        ),
    ]
