# Generated by Django 2.2.6 on 2019-10-23 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20191023_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_achado',
            name='imagem',
            field=models.ImageField(upload_to='upload_photo'),
        ),
    ]
