# Generated by Django 2.2.6 on 2019-10-23 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20191023_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_achado',
            name='imagem',
            field=models.ImageField(blank=True, upload_to='upload_photo', verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='item_perdido',
            name='imagem',
            field=models.ImageField(blank=True, upload_to='upload_photo', verbose_name='Imagem'),
        ),
    ]
